// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOSsgkvQufwwnXJpFEQtgeq7hCCmEExCI',
    appId: '1:719790808121:web:470aaff2e831a735ab81e8',
    messagingSenderId: '719790808121',
    projectId: 'esaudagar-65583',
    authDomain: 'esaudagar-65583.firebaseapp.com',
    storageBucket: 'esaudagar-65583.firebasestorage.app',
    measurementId: 'G-P4QZTV2CZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAlgyKyKa6_XgEed4uXQDPKCqmLDIivVk',
    appId: '1:719790808121:android:deab59db7e2af182ab81e8',
    messagingSenderId: '719790808121',
    projectId: 'esaudagar-65583',
    storageBucket: 'esaudagar-65583.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuTaGiVHa2h8Tj8NvaLvkoVkhZxZvzpCU',
    appId: '1:719790808121:ios:8c9f6622b886f409ab81e8',
    messagingSenderId: '719790808121',
    projectId: 'esaudagar-65583',
    storageBucket: 'esaudagar-65583.firebasestorage.app',
    iosClientId: '719790808121-8f7le7jrt25ccd6hi3hvavgj46sjq7nv.apps.googleusercontent.com',
    iosBundleId: 'com.example.esaudagar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuTaGiVHa2h8Tj8NvaLvkoVkhZxZvzpCU',
    appId: '1:719790808121:ios:8c9f6622b886f409ab81e8',
    messagingSenderId: '719790808121',
    projectId: 'esaudagar-65583',
    storageBucket: 'esaudagar-65583.firebasestorage.app',
    iosClientId: '719790808121-8f7le7jrt25ccd6hi3hvavgj46sjq7nv.apps.googleusercontent.com',
    iosBundleId: 'com.example.esaudagar',
  );
}
